# PostgreSQL configuration
default: &default
  adapter: postgresql
  encoding: unicode
  username: motion
  password: motion
  host: localhost
  port: 5434
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  primary:
    <<: *default
    database: slx_development
  queue:
    <<: *default
    database: slx_development
    migrations_paths: db/queue_migrate

test:
  primary:
    <<: *default
    database: slx_test
  queue:
    <<: *default
    database: slx_test
    migrations_paths: db/queue_migrate

production:
  primary:
    adapter: postgresql
    encoding: unicode
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    url: <%= ENV["DATABASE_URL"] %>
  queue:
    adapter: postgresql
    encoding: unicode
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    url: <%= ENV["DATABASE_URL"] %>
    migrations_paths: db/queue_migrate
